output_dir: "/n/scratch/users/s/sak0914/immunology_project"
fastq_dir: "/n/data1/hms/dbmi/farhat/rollingDB/fastq_db"
isolates_to_run: "/home/sak0914/Mtb_Megapipe/immunology_samples.tsv"
kraken_db: "./kraken_db/custom_human_MTBC"
kraken_unclassified_max: 15
scripts_dir: "./scripts"
references_dir: "./references"
min_read_length: 50
median_depth: 15
min_cov: 20
genome_cov_prop: 0.95
annot_VCF_name: "./VCFs_to_annot.txt"
snpEff_db: "Mycobacterium_tuberculosis_h37rv"