output_dir: "/n/data1/hms/dbmi/farhat/rollingDB/genomic_data"
fastq_dir: "/n/data1/hms/dbmi/farhat/rollingDB/fastq_db"
isolates_to_run: "/home/sak0914/Mtb_Megapipe/isolates_to_run.tsv"
kraken_db: "/home/sak0914/Mtb_Megapipe/kraken_db/custom_human_MTBC"
kraken_unclassified_max: 10
scripts_dir: "./scripts"
references_dir: "./references"
min_read_length: 50
median_depth: 15
min_cov: 20
genome_cov_prop: 0.95
annot_VCF_name: "./VCFs_to_annot.txt"
snpEff_db: "Mycobacterium_tuberculosis_h37rv"
kraken2_confidence: 0
kraken2_minimum_hit_groups: 2
taxid: 77643
bwa_mem_seed_length: 19