output_dir: "/n/data1/hms/dbmi/farhat/rollingDB/TRUST/Illumina_culture_WGS_processed"
fastq_dir: "/n/scratch/users/s/sak0914/TRUST_FASTQ"
isolates_to_run: "/home/sak0914/Mtb_Megapipe/TRUST_samples.tsv"
kraken_db: "/n/data1/hms/dbmi/farhat/mm774/References/Kraken2_DB_Dir/Kraken2_DB" #"./kraken_db/custom_human_MTBC"
kraken_unclassified_max: 15
scripts_dir: "./scripts"
references_dir: "./references"
min_read_length: 50
median_depth: 15
min_cov: 20
genome_cov_prop: 0.90
annot_VCF_name: "./VCFs_to_annot.txt"
snpEff_db: "Mycobacterium_tuberculosis_h37rv"