output_dir:
fastq_dir:
isolates_to_run:
kraken_db: "./kraken_db/custom_human_MTBC"
kraken_unclassified_max: 10
scripts_dir: "./scripts"
references_dir: "./references"
min_read_length: 50
median_depth: 15
min_cov: 10
genome_cov_prop: 0.90
annot_VCF_name: "./VCFs_to_annot.txt"
snpEff_db: "Mycobacterium_tuberculosis_h37rv"
kraken2_confidence: 0
kraken2_minimum_hit_groups: 2
taxid: 77643
bwa_mem_seed_length: 19
exclude_regions_file: "./BED_files/exclude_regions_50bp.bed" #"BED_files/RLC_Regions.Plus.LowPmapK50E4.H37Rv.bed"
phase_variation_ROI_file: "./BED_files/phase_variation_ROI.bed"
WHO_catalog_regions_file: "./BED_files/WHO_catalog_regions.bed"
