output_dir: "/n/data1/hms/dbmi/farhat/rollingDB/genomic_data" #"/n/data1/hms/dbmi/farhat/rollingDB/TRUST/Illumina_culture_WGS_processed"
fastq_dir: "/n/data1/hms/dbmi/farhat/rollingDB/fastq_db"
isolates_to_run: "/home/sak0914/Mtb_Megapipe/IDR_samples_run.tsv"
kraken_db: "./kraken_db/custom_human_MTBC"
kraken_unclassified_max: 50
scripts_dir: "./scripts"
references_dir: "./references"
min_read_length: 50
median_depth: 15
min_cov: 20
genome_cov_prop: 0.25
annot_VCF_name: "./VCFs_to_annot.txt"
snpEff_db: "Mycobacterium_tuberculosis_h37rv"